Rowery/Controllers/RowersController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using Microsoft.AspNetCore.Authorization;
using Rowery.Models;
using Rowery.Data;
using Rowery.Models;



namespace WypozyczalniaRowerow.Controllers
{
    public class RowersController : Controller
    {

        private readonly RoweryContext _context;

        public RowersController(RoweryContext context)
        {
            _context = context;
        }


        // GET: /HelloWorld/
        public IActionResult Glowna()
        {

            return View();
        }
        // 
        // GET: /HelloWorld/Welcome/ 
        public async Task<IActionResult> Oferta()
        {
            return View(await _context.Rower.ToListAsync());
        }
        public IActionResult Kontakt()
        {
            return View();
        }
        public IActionResult Privacy()
        {
            ViewData["Message"] = "Hello";
            ViewData["NumTimes"] = 10;
            return View();
        }

        // GET: Rowers
        [Authorize(Roles="Admin")]
        public async Task<IActionResult> Index()
        {
            return View(await _context.Rower.ToListAsync());
        }

        // GET: Rowers/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var rower = await _context.Rower
                .FirstOrDefaultAsync(m => m.Id == id);
            if (rower == null)
            {
                return NotFound();
            }

            return View(rower);
        }

        // GET: Rowers/Create
        public IActionResult Create()
        {
            return View();
        }

        // POST: Rowers/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("Id,Name,Price,IsAvailable,url_img,brand,Weight,ReleaseDate")] Rower rower)
        {
            if (ModelState.IsValid)
            {
                _context.Add(rower);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            return View(rower);
        }

        // GET: Rowers/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var rower = await _context.Rower.FindAsync(id);
            if (rower == null)
            {
                return NotFound();
            }
            return View(rower);
        }



        [HttpPost]
        public IActionResult ToggleAvailability(int id, int selectedOption, string rentDate)
        {
            var rower = _context.Rower.Find(id);

            if (rower != null)
            {
                int daysToAdd = selectedOption;

                // Ustaw datę wypożyczenia
                rower.RentDate = DateTime.Now;
                // Dodaj ilość dni do daty zwrotu
                rower.ReturnDate = rower.RentDate.AddDays(daysToAdd);

                // Zmień dostępność
                rower.IsAvailable = !rower.IsAvailable;

                // Zapisz zmiany w bazie danych
                _context.SaveChanges();
            }

            // Przekieruj na potwierdzenie
            return RedirectToAction("Oferta");
        }


        // POST: Rowers/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("Id,Name,Price,IsAvailable,url_img,brand,Weight,ReleaseDate,RentDate,ReturnDate")] Rower rower)
        {
            if (id != rower.Id)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(rower);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!RowerExists(rower.Id))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            return View(rower);
        }

        // GET: Rowers/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var rower = await _context.Rower
                .FirstOrDefaultAsync(m => m.Id == id);
            if (rower == null)
            {
                return NotFound();
            }

            return View(rower);
        }

        // POST: Rowers/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            var rower = await _context.Rower.FindAsync(id);
            if (rower != null)
            {
                _context.Rower.Remove(rower);
            }

            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool RowerExists(int id)
        {
            return _context.Rower.Any(e => e.Id == id);
        }
    }
}

Rowery/Views/Rowers/Create.cshtml
@model Rowery.Models.Rower

@{
    ViewData["Title"] = "Create";
}

<h1>Create</h1>

<h4>Rower</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Create">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                <label asp-for="Name" class="control-label"></label>
                <input asp-for="Name" class="form-control" />
                <span asp-validation-for="Name" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Price" class="control-label"></label>
                <input asp-for="Price" class="form-control" />
                <span asp-validation-for="Price" class="text-danger"></span>
            </div>
            <div class="form-group form-check">
                <label class="form-check-label">
                    <input class="form-check-input" asp-for="IsAvailable" /> @Html.DisplayNameFor(model => model.IsAvailable)
                </label>
            </div>
            <div class="form-group">
                <label asp-for="url_img" class="control-label"></label>
                <input asp-for="url_img" class="form-control" />
                <span asp-validation-for="url_img" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="brand" class="control-label"></label>
                <input asp-for="brand" class="form-control" />
                <span asp-validation-for="brand" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Weight" class="control-label"></label>
                <input asp-for="Weight" class="form-control" />
                <span asp-validation-for="Weight" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="ReleaseDate" class="control-label"></label>
                <input asp-for="ReleaseDate" class="form-control" />
                <span asp-validation-for="ReleaseDate" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="RentDate" class="control-label"></label>
                <input asp-for="RentDate" class="form-control" />
                <span asp-validation-for="RentDate" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="ReturnDate" class="control-label"></label>
                <input asp-for="ReturnDate" class="form-control" />
                <span asp-validation-for="ReturnDate" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Create" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

Rowery/Views/Rowers/Delete.cshtml
@model Rowery.Models.Rower

@{
    ViewData["Title"] = "Delete";
}

<h1>Delete</h1>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>Rower</h4>
    <hr />
    <dl class="row">
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Name)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Name)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Price)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Price)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.IsAvailable)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.IsAvailable)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.url_img)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.url_img)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.brand)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.brand)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Weight)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Weight)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.ReleaseDate)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.ReleaseDate)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.RentDate)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.RentDate)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.ReturnDate)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.ReturnDate)
        </dd>
    </dl>
    
    <form asp-action="Delete">
        <input type="hidden" asp-for="Id" />
        <input type="submit" value="Delete" class="btn btn-danger" /> |
        <a asp-action="Index">Back to List</a>
    </form>
</div>

Rowery/Views/Rowers/Details.cshtml
@model Rowery.Models.Rower

@{
    ViewData["Title"] = "Details";
}

<h1>Details</h1>

<div>
    <h4>Rower</h4>
    <hr />
    <dl class="row">
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Name)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Name)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Price)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Price)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.IsAvailable)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.IsAvailable)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.url_img)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.url_img)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.brand)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.brand)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Weight)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Weight)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.ReleaseDate)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.ReleaseDate)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.RentDate)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.RentDate)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.ReturnDate)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.ReturnDate)
        </dd>
    </dl>
</div>
<div>
    <a asp-action="Edit" asp-route-id="@Model?.Id">Edit</a> |
    <a asp-action="Index">Back to List</a>
</div>

Rowery/Views/Rowers/Edit.cshtml
@model Rowery.Models.Rower

@{
    ViewData["Title"] = "Edit";
}

<h1>Edit</h1>

<h4>Rower</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Edit">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <input type="hidden" asp-for="Id" />
            <div class="form-group">
                <label asp-for="Name" class="control-label"></label>
                <input asp-for="Name" class="form-control" />
                <span asp-validation-for="Name" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Price" class="control-label"></label>
                <input asp-for="Price" class="form-control" />
                <span asp-validation-for="Price" class="text-danger"></span>
            </div>
            <div class="form-group form-check">
                <label class="form-check-label">
                    <input class="form-check-input" asp-for="IsAvailable" /> @Html.DisplayNameFor(model => model.IsAvailable)
                </label>
            </div>
            <div class="form-group">
                <label asp-for="url_img" class="control-label"></label>
                <input asp-for="url_img" class="form-control" />
                <span asp-validation-for="url_img" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="brand" class="control-label"></label>
                <input asp-for="brand" class="form-control" />
                <span asp-validation-for="brand" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Weight" class="control-label"></label>
                <input asp-for="Weight" class="form-control" />
                <span asp-validation-for="Weight" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="ReleaseDate" class="control-label"></label>
                <input asp-for="ReleaseDate" class="form-control" />
                <span asp-validation-for="ReleaseDate" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="RentDate" class="control-label"></label>
                <input asp-for="RentDate" class="form-control" />
                <span asp-validation-for="RentDate" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="ReturnDate" class="control-label"></label>
                <input asp-for="ReturnDate" class="form-control" />
                <span asp-validation-for="ReturnDate" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Save" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

Rowery/Views/Rowers/Glowna.cshtml
@{
    ViewData["Title"] = "Strona Główna";
}<head>
    <!-- Dodanie Bootstrap CSS -->
    <style>
       
        header {
            background-color: #f8f9fa;
        }

        .jumbotron {
            background-image: url('https://a.assecobs.com/_img/wmbikesb2c/005cc7f8-a5c0-4ca8-870e-65f609c290a3/rower-cube-aim-slx-601500-l-20-.jpg');
            background-size: cover;
            color: white;
            text-align: center;
            padding: 100px 20px;
            margin-bottom: 0;
        }

        .feature-box {
            text-align: center;
            margin: 40px 0;
        }

        .feature-icon {
            font-size: 3em;
            margin-bottom: 10px;
        }
    </style>
</head>

<br />
<div class="jumbotron">
    <h1 class="display-4">Witaj w wypożyczalni Maglownica!</h1>
    <p class="lead">Naszą misją jest wypożyczanie rowerów na każdą okazję i w każdej chwili.</p>
    <hr class="my-4">
    <p>Sprawdź naszą różnorodną ofertę</p>
    <a class="btn btn-primary btn-lg" href="Rowers/oferta" role="button">Oferta</a>
</div>




<div class="container">
    <div class="row">
        <div class="col-md-4 feature-box">
            <i class="feature-icon fas fa-rocket"></i>
            <h3>Szybkość</h3>
            <p>Szybkie i efektywne usługi dostosowane do Twoich potrzeb.</p>
        </div>
        <div class="col-md-4 feature-box">
            <i class="feature-icon fas fa-cogs"></i>
            <h3>Elastyczność</h3>
            <p>Elastyczność w dostosowywaniu naszych usług do Twoich oczekiwań.</p>
        </div>
        <div class="col-md-4 feature-box">
            <i class="feature-icon fas fa-heart"></i>
            <h3>Pasja</h3>
            <p>Z pasją i zaangażowaniem dostarczamy najlepsze rozwiązania dla naszych klientów.</p>
        </div>
    </div>
</div>
<!-- Sekcja z funkcjami/usługami -->

<div class="container marketing">


    <!-- START THE FEATURETTES -->

    <hr class="featurette-divider">

    <div class="row featurette">
        <div class="col-md-7">
            <h2 class="featurette-heading fw-normal lh-1">Razem czy osobno? Wypróbuj jeden z historycznych rowerów</h2>
            <p class="lead">Zapomnij o zwykłych spacerach czy tradycyjnych rowerach – teraz możesz poczuć się jak bohater filmu, przemierzając ulice miasta w stylu. Rikszą podróż jest nie tylko ekscytująca, ale również ekologiczna, co sprawia, że Twoje doświadczenie staje się jeszcze bardziej satysfakcjonujące.</p>
        </div>
        <div class="col-md-5 pierwszy">
            <img class="bd-placeholder-img bd-placeholder-img-lg featurette-image img-fluid mx-auto" width="500" height="500" src="https://indigodecor.pl/wp-content/uploads/2020/04/riksza-indigodecor-pl-600x401.jpg" />
        </div>
    </div>

    <hr class="featurette-divider">

    <div class="row featurette">
        <div class="col-md-7 order-md-2">
            <h2 class="featurette-heading fw-normal lh-1">A może jesteś profesjonalistą i potrzebujesz roweru, który da radę w trudnych warunkach? </h2>
            <p class="lead">Nasze rowery górskie są wyposażone w zaawansowane technologie, które pozwalają radzić sobie z różnorodnym terenem. Bez względu na to, czy zmierzasz na wymagające szlaki górskie, zakręcone ścieżki leśne czy kamieniste tereny, nasze rowery są gotowe na każde wyzwanie.</p>
        </div>
        <div class="col-md-5 order-md-1">
            <img class="bd-placeholder-img bd-placeholder-img-lg featurette-image img-fluid mx-auto" width="500" height="500" src="https://www.cyclo-centrum.pl/wp-content/uploads/2021/04/marlin7-trek-rower.jpg" />
        </div>
    </div>

    <hr class="featurette-divider">
</div>
<div class="container marketing">

    <!-- Three columns of text below the carousel -->
    <div class="row">
        <div class="col-lg-4">
            <img class="rounded-circle" src="https://thispersondoesnotexist.com/" alt="Generic placeholder image" width="140" height="140">
            <h2>Niesamowity kontakt z klientem</h2>
            <p>Dziękuję na ślubie Riksza była niesamowitą atrakcją serdecznie polecam!</p>
        </div><!-- /.col-lg-4 -->
        <div class="col-lg-4">
            <img class="rounded-circle" src="https://thispersondoesnotexist.com/" alt="Generic placeholder image" width="140" height="140">
            <h2>Profesjonalizm</h2>
            <p>Dziekuję Bardzo! Dzięki patronatowi oraz sprzętowi z "Maglownicy" udało mi sie ukończyć Triathlon mam nadzieję że to nie koniec współpracy. Polecam!</p>
        </div><!-- /.col-lg-4 -->
        <div class="col-lg-4">
            <img class="rounded-circle" src="https://thispersondoesnotexist.com/" alt="Generic placeholder image" width="140" height="140">
            <h2>Szybka obsługa</h2>
            <p>Fenomenalna obsługa! Zadzwoniłem, a po dwóch godzinach rowery były gotowe do jazdy. Dzięki temu pojechaliśmy całą rodziną na przejażdżkę po górach dzięki!</p>
        </div><!-- /.col-lg-4 -->
    </div><!-- /.row -->

   
</div>
<h1>80% zadowolonych klientów!</h1>
<div class="progress">

    <div class="progress-bar progress-bar-striped progress-bar-animated" role="progressbar" aria-valuenow="74" aria-valuemin="0" aria-valuemax="75" style="width: 75%"></div>
</div>

Rowery/Views/Rowers/Index.cshtml
@model IEnumerable<Rowery.Models.Rower>

@{
    ViewData["Title"] = "Index";
}

<h1>Index</h1>

<p>
    <a asp-action="Create">Create New</a>
</p>
<table class="table">
    <thead>
        <tr>
            <th>
                @Html.DisplayNameFor(model => model.Name)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Price)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.IsAvailable)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.url_img)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.brand)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Weight)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.ReleaseDate)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.RentDate)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.ReturnDate)
            </th>
        </tr>
    </thead>
    <tbody>
@foreach (var item in Model) {
        <tr>
            <td>
                @Html.DisplayFor(modelItem => item.Name)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Price)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.IsAvailable)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.url_img)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.brand)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Weight)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.ReleaseDate)
            </td>
                <td>
                    @Html.DisplayFor(modelItem => item.RentDate)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.ReturnDate)
                </td>
            <td>
                <a asp-action="Edit" asp-route-id="@item.Id">Edit</a> |
                <a asp-action="Details" asp-route-id="@item.Id">Details</a> |
                <a asp-action="Delete" asp-route-id="@item.Id">Delete</a>
            </td>
        </tr>
}
    </tbody>
</table>

Rowery/Views/Rowers/Oferta.cshtml
@model IEnumerable<Rowery.Models.Rower>
@using Microsoft.AspNetCore.Identity

@inject SignInManager<IdentityUser> SignInManager
@inject UserManager<IdentityUser> UserManager

@{
    ViewData["Title"] = "Oferta";
}

<h2>Oferta</h2>
<div style="Flex-wrap: wrap;" class="d-flex p-2 bd-highlight">
@foreach (var item in Model)
{
            var tydzien = item.Price*3*0.95;
            var miesiac =  item.Price * 13*0.9;
            
        
    
    
     
                <div class="col-sm-4">
            <div class="card margines_daj">
                        <img src="@Html.DisplayFor(modelItem => item.url_img)" height="250px"  class="card-img-top" width="100%">

                <div class="card-body pt-0 px-0">
                            <h3 class="card-title do_srodka">@Html.DisplayFor(modelItem => item.Name)</h3>
                    <div class="d-flex flex-row justify-content-between mb-0 px-3">

                                <small class="text-muted mt-1">Cena za 2 dni: </small>
                                <h6>@Html.DisplayFor(modelItem => item.Price) zł</h6>
                    </div>
                            <div class="d-flex flex-row justify-content-between mb-0 px-3">
                                <small class="text-muted mt-1">Cena za 7 dni: </small>
                                <h6>@tydzien zł</h6>
                            </div>
                            <div class="d-flex flex-row justify-content-between mb-0 px-3">
                                <small class="text-muted mt-1">Cena za 30 dni: </small>
                                <h6>@miesiac zł</h6>
                            </div>
                    <hr class="mt-2 mx-3">
                    <div class="d-flex flex-row justify-content-between px-3 pb-4">
                                <div class="d-flex flex-column"><span class="text-muted">Marka: </span><small class="text-muted">@Html.DisplayFor(modelItem => item.brand)</small></div>
                                <div class="d-flex flex-column"><h5 class="mb-0">Waga:</h5><small class="text-muted text-right">@Html.DisplayFor(modelItem => item.Weight)kg</small></div>
                        
                        
                    </div>
                    <div class="mx-3 mt-3 mb-2 text-center">
                    @if (item.ReturnDate != null && item.ReturnDate != DateTime.MinValue && item.IsAvailable == false)
                    {
                        <div class="d-flex flex-column">
                            <h5 class="mb-0">Przedmiot niedostępny!</h5>
                            <small class="text-muted text-right">Zwrot nastąpi @item.ReturnDate</small>
                        </div>
                    }
                    </div>
                    @if(User.Identity.IsAuthenticated)
                    {
                              
                    <div class="mx-3 mt-3 mb-2 text-center">
                        @{
                            if (item.IsAvailable)
                            {
                                <button type="button" class="btn btn-primary" data-bs-toggle="modal" data-bs-target="#wybierzOpcjeModal-@item.Id">
                                    Wypożycz
                                </button>
                                
                            }
                            else
                            {
                                    <a href="#" class="btn btn-danger disabled">Niedostępny</a>
                                }
                            }
                        </div>
                    }
                    else
                    {
                        <div class="mx-3 mt-3 mb-2 text-center">
                            @{

                                <button type="button" class="btn btn-primary" data-bs-toggle="modal" data-bs-target="/Account/Login">
                                    <a class="nav-link text-white" asp-area="Identity" asp-page="/Account/Login">Aby Wypożyczyć zaloguj się!</a>
                                    </button>

                                
                            }
                        </div>
                    }
                    


                    <!-- Modal -->
                    <div class="modal fade" id="wybierzOpcjeModal-@item.Id" tabindex="-1" aria-labelledby="wybierzOpcjeModalLabel-@item.Id" aria-hidden="true">
                        <div class="modal-dialog">
                            <div class="modal-content">
                                <div class="modal-header">
                                    <h5 class="modal-title" id="wybierzOpcjeModalLabel">Wybierz opcje</h5>
                                    <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
                                </div>
                                <div class="modal-body">
                                    <div class="form-group">
                                        <label for="exampleFormControlSelect2">Wybierz na ile chcesz wypożyczyć Rower</label>
                                        <select name="selectedOption" class="form-control" id="exampleFormControlSelect2-@item.Id">
                                            <option value="" disabled selected>Wybierz opcję</option>
                                            <option value="2">2 dni - @Html.DisplayFor(modelItem => item.Price) zł</option>
                                            <option value="7">7 dni - @tydzien zł</option>
                                            <option value="30">30 dni - @miesiac zł</option>
                                        </select>
                                    </div>
                                </div>
                                <div class="modal-footer">
                                    <form method="post" action="@Url.Action("ToggleAvailability", "Rowers")">
                                        @Html.Hidden("id", item.Id)
                                        <!-- Użyj unikalnego identyfikatora dla ukrytego pola -->
                                        <input type="hidden" name="selectedOption" id="selectedOptionHidden-@item.Id" />
                                        <input type="hidden" name="rentDate" value="@DateTime.Now.ToString("dd-MM-yyyy")" />
                                        <button type="submit" class="btn btn-primary">Wypożycz</button>
                                    </form>
                                </div>
                                <script>
                                    var selectedOptionValue = 2;
                                    $(document).ready(function () {
                                        

                                        // Użyj unikalnego identyfikatora dla elementu select i ukrytego pola
                                        $('#exampleFormControlSelect2-@item.Id').change(function () {
                                            selectedOptionValue = $(this).val();
                                            console.log('Wybrana opcja: ' + selectedOptionValue);

                                            // Ustaw wartość w ukrytym polu formularza
                                            $('#selectedOptionHidden-@item.Id').val(selectedOptionValue);
                                        });
                                    });
                                </script>
                            </div>
                        </div>
                    </div>
                        </div>
                    </div>
                </div>

          
        

    }
</div>